version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "integrations/github"
